In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
# 수치 미분
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    # print("debug 1. initial input variable =", x)
    # print("debug 2. initial input grad =", grad)
    # print("="*25)
    
    it = np.nditer(x,flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        #  print("debug 3. idx=", idx, ", x[idx]=",x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx]=(fx1- fx2) / (2*delta_x)
        
        # print("debug 4. grad[idx] = ", grad[idx])
        # print("debug 5. grad = ", grad)
        # print("="*25)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [4]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        self.__xdata = xdata
        self.__tdata = tdata
        
        self.__xdata = xdata.reshape(4,2)
        self.__tdata = tdata.reshape(4,1)
        
        self.__W2 = np.random.rand(2,6)
        self.__b2 = np.random.rand(6)
        
        self.__W3 = np.random.rand(6,1)
        self.__b3 = np.random.rand(1)
        
        self.__learning_rate = 1e-2
    
    def feed_forward(self):
        delta = 1e-7
        
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3)+self.__b3
        y=sigmoid(z3)
        
        return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y) + delta))
        
    
    def train(self):
        f=lambda x: self.feed_forward()

        print("Initial loss_func :", self.feed_forward())

        for step in range(10001):
            self.__W2 -= self.__learning_rate*numerical_derivative(f,self.__W2)
            self.__b2 -= self.__learning_rate*numerical_derivative(f,self.__b2)
            
            self.__W3 -= self.__learning_rate*numerical_derivative(f,self.__W3)
            self.__b3 -= self.__learning_rate*numerical_derivative(f,self.__b3)

            if step%400==0:
                print("step :",step,"// loss value :", self.feed_forward())
    
    def predict(self, xdata):
        z2 = np.dot(xdata,self.__W2) +self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3) + self.__b3
        y = sigmoid(z3)

        if y > 0.5:
            result = 1  # True
        else:
            result = 0  # False
        
        return y, result

In [5]:
# AND 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 0,0,0,1 ])

AND_obj = LogicGate("AND_GATE", xdata, tdata)
AND_obj.train()

Initial loss_func : 9.800400622997586
step : 0 // loss value : 9.486368997017669
step : 400 // loss value : 2.157162051142102
step : 800 // loss value : 1.9125229127139085
step : 1200 // loss value : 1.5323960337087348
step : 1600 // loss value : 1.167609330546732
step : 2000 // loss value : 0.8684858099697783
step : 2400 // loss value : 0.6406076636179565
step : 2800 // loss value : 0.47817110398980867
step : 3200 // loss value : 0.36562348450059723
step : 3600 // loss value : 0.2874192098625653
step : 4000 // loss value : 0.23201693529522666
step : 4400 // loss value : 0.1917542763392119
step : 4800 // loss value : 0.1617149983655905
step : 5200 // loss value : 0.13874282425606382
step : 5600 // loss value : 0.12077899430839595
step : 6000 // loss value : 0.10645096599120855
step : 6400 // loss value : 0.09482195682167466
step : 6800 // loss value : 0.0852376824944058
step : 7200 // loss value : 0.07723111259444165
step : 7600 // loss value : 0.07046209966447936
step : 8000 // loss v

In [6]:
# AND Gate prediction
print(AND_obj.name)

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for data in test_data:
    print(AND_obj.predict(data))

AND_GATE
(array([0.00025255]), 0)
(array([0.01163411]), 0)
(array([0.01145328]), 0)
(array([0.97850351]), 1)


In [7]:
# OR 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 0,1,1,1 ])

OR_obj = LogicGate("OR_GATE", xdata, tdata)
OR_obj.train()

Initial loss_func : 2.742577487980257
step : 0 // loss value : 2.7228688279932314
step : 400 // loss value : 1.9860729254974687
step : 800 // loss value : 1.7755875553998175
step : 1200 // loss value : 1.4563044332839117
step : 1600 // loss value : 1.0782655081643644
step : 2000 // loss value : 0.7489318617795314
step : 2400 // loss value : 0.5181204905099542
step : 2800 // loss value : 0.3700960011824841
step : 3200 // loss value : 0.27568168332709975
step : 3600 // loss value : 0.2136316088877849
step : 4000 // loss value : 0.17120429622536337
step : 4400 // loss value : 0.1410445924985297
step : 4800 // loss value : 0.1188468787820115
step : 5200 // loss value : 0.10201046335919399
step : 5600 // loss value : 0.08890763701182422
step : 6000 // loss value : 0.07848369384987947
step : 6400 // loss value : 0.07003296779691597
step : 6800 // loss value : 0.06306947755348298
step : 7200 // loss value : 0.05724977781620975
step : 7600 // loss value : 0.05232550274408419
step : 8000 // los

In [8]:
# OR Gate prediction
print(OR_obj.name)

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for data in test_data:
    print( OR_obj.predict(data))

OR_GATE
(array([0.01949352]), 0)
(array([0.99319138]), 1)
(array([0.99293136]), 1)
(array([0.99973245]), 1)


In [9]:
# NAND 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 1,1,1,0 ])

NAND_obj = LogicGate("NAND_GATE", xdata, tdata)
NAND_obj.train()

Initial loss_func : 3.2046413796002238
step : 0 // loss value : 3.1781957094155566
step : 400 // loss value : 2.3437621958954282
step : 800 // loss value : 2.230666675069466
step : 1200 // loss value : 2.0585859014791694
step : 1600 // loss value : 1.7924098223768412
step : 2000 // loss value : 1.4652949703218008
step : 2400 // loss value : 1.1260976179718432
step : 2800 // loss value : 0.8277298826765087
step : 3200 // loss value : 0.6029136169502268
step : 3600 // loss value : 0.4477482235497027
step : 4000 // loss value : 0.34278113844696667
step : 4400 // loss value : 0.2706771720060941
step : 4800 // loss value : 0.21974493542658816
step : 5200 // loss value : 0.18266404822385363
step : 5600 // loss value : 0.15488582338295714
step : 6000 // loss value : 0.1335365064697495
step : 6400 // loss value : 0.11675450934901105
step : 6800 // loss value : 0.10330086912935557
step : 7200 // loss value : 0.09232897353782527
step : 7600 // loss value : 0.0832458774499493
step : 8000 // loss 

In [10]:
# NAND Gate prediction
print(NAND_obj.name)

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for data in test_data:
    print(NAND_obj.predict(data))

NAND_GATE
(array([0.99977582]), 1)
(array([0.98665456]), 1)
(array([0.9878981]), 1)
(array([0.02481014]), 0)


In [11]:
# XOR 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 0,1,1,0 ])

XOR_obj = LogicGate("XOR_GATE", xdata, tdata)
XOR_obj.train()

Initial loss_func : 4.741148588634095
step : 0 // loss value : 4.628088926061649
step : 400 // loss value : 2.764518200767805
step : 800 // loss value : 2.759695805308941
step : 1200 // loss value : 2.7539770384565516
step : 1600 // loss value : 2.74668736445109
step : 2000 // loss value : 2.7369565680068852
step : 2400 // loss value : 2.723598851214584
step : 2800 // loss value : 2.7049657238571254
step : 3200 // loss value : 2.6787734430494403
step : 3600 // loss value : 2.641979764783395
step : 4000 // loss value : 2.59098540767772
step : 4400 // loss value : 2.5226725483097345
step : 4800 // loss value : 2.436373727866629
step : 5200 // loss value : 2.3351912261072756
step : 5600 // loss value : 2.2245280775419234
step : 6000 // loss value : 2.1086672747178037
step : 6400 // loss value : 1.9882161956730602
step : 6800 // loss value : 1.8594247496982095
step : 7200 // loss value : 1.715551302289703
step : 7600 // loss value : 1.5518243484315326
step : 8000 // loss value : 1.37192371

In [12]:
# XOR Gate prediction
print(XOR_obj.name)

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for data in test_data:
    print(XOR_obj.predict(data))

XOR_GATE
(array([0.05036063]), 0)
(array([0.83860692]), 1)
(array([0.86301701]), 1)
(array([0.22194216]), 0)
