In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
# 수치 미분
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    # print("debug 1. initial input variable =", x)
    # print("debug 2. initial input grad =", grad)
    # print("="*25)
    
    it = np.nditer(x,flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        #  print("debug 3. idx=", idx, ", x[idx]=",x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx]=(fx1- fx2) / (2*delta_x)
        
        # print("debug 4. grad[idx] = ", grad[idx])
        # print("debug 5. grad = ", grad)
        # print("="*25)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [4]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        self.__xdata = xdata.reshape(4,2)
        self.__tdata = tdata.reshape(4,1)
        
        self.__W = np.random.rand(2,1)
        self.__b = np.random.rand(1)
        
        self.__learning_rate = 1e-2
    
    def __loss_func(self):
        delta = 1e-7
        z = np.dot(self.__xdata, self.__W) + self.__b
        y = sigmoid(z)
        
        return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y) + delta))
    
    def train(self):
        f=lambda x: self.__loss_func()

        print("Initial loss_func :", self.__loss_func())

        for step in range(8001):
            self.__W -= self.__learning_rate*numerical_derivative(f,self.__W)
            self.__b -= self.__learning_rate*numerical_derivative(f,self.__b)

            if step%400==0:
                print("step",step,"error value=", self.__loss_func())
    
    def predict(self, input_data):
        z = np.dot(input_data,self.__W) +self.__b
        y = sigmoid(z)

        if y > 0.5:
            result = 1  # True
        else:
            result = 0  # False
        
        return y, result

In [5]:
# AND 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 0,0,0,1 ])

AND_obj = LogicGate("AND_GATE", xdata, tdata)
AND_obj.train()

Initial loss_func : 3.1023102680045804
step 0 error value= 3.0782579687492615
step 400 error value= 1.5276405713771608
step 800 error value= 1.137416784817008
step 1200 error value= 0.9153959918328454
step 1600 error value= 0.7685836780361044
step 2000 error value= 0.6629408345394439
step 2400 error value= 0.582780411150259
step 2800 error value= 0.5196931691760506
step 3200 error value= 0.4686876441239438
step 3600 error value= 0.4265803805910242
step 4000 error value= 0.3912306949139286
step 4400 error value= 0.3611395538141407
step 4800 error value= 0.33522299800095423
step 5200 error value= 0.31267644799565514
step 5600 error value= 0.2928895437607112
step 6000 error value= 0.2753906163188178
step 6400 error value= 0.25980931097623094
step 6800 error value= 0.24585074287711414
step 7200 error value= 0.23327720951000203
step 7600 error value= 0.22189498835805788
step 8000 error value= 0.2115446362017085


In [6]:
# AND Gate prediction
print(AND_obj.name, '\n')

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for input_data in test_data:
    (sigmoidid_val, logical_val) = AND_obj.predict(input_data)
    print( input_data, ' = ', logical_val, '\n')

AND_GATE 

[0 0]  =  0 

[0 1]  =  0 

[1 0]  =  0 

[1 1]  =  1 



In [7]:
# OR 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 0,1,1,1 ])

OR_obj = LogicGate("OR_GATE", xdata, tdata)
OR_obj.train()

Initial loss_func : 1.9672567140779404
step 0 error value= 1.9622947774062927
step 400 error value= 1.1763126369656334
step 800 error value= 0.8397341951123481
step 1200 error value= 0.6464103825655947
step 1600 error value= 0.5221985446339983
step 2000 error value= 0.4361928164143382
step 2400 error value= 0.37341754733222576
step 2800 error value= 0.3257581403664932
step 3200 error value= 0.2884482075650159
step 3600 error value= 0.25851262143135956
step 4000 error value= 0.23400358888619446
step 4400 error value= 0.21359562958407294
step 4800 error value= 0.1963573313886229
step 5200 error value= 0.18161619489252914
step 5600 error value= 0.168875233133696
step 6000 error value= 0.15775967652810213
step 6400 error value= 0.14798187459506182
step 6800 error value= 0.13931756650669289
step 7200 error value= 0.13158946266443122
step 7600 error value= 0.12465564910853803
step 8000 error value= 0.11840124627690964


In [8]:
# OR Gate prediction
print(OR_obj.name, '\n')

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for input_data in test_data:
    (sigmoidid_val, logical_val) = OR_obj.predict(input_data)
    print( input_data, ' = ', logical_val, '\n')

OR_GATE 

[0 0]  =  0 

[0 1]  =  1 

[1 0]  =  1 

[1 1]  =  1 



In [9]:
# NAND 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 1,1,1,0 ])

NAND_obj = LogicGate("NAND_GATE", xdata, tdata)
NAND_obj.train()

Initial loss_func : 3.193629191689019
step 0 error value= 3.183753211571168
step 400 error value= 1.7095345594662867
step 800 error value= 1.2281120105910626
step 1200 error value= 0.9711206871974465
step 1600 error value= 0.8069431594675782
step 2000 error value= 0.6912062786441561
step 2400 error value= 0.6045653794581559
step 2800 error value= 0.5370303768551681
step 3200 error value= 0.4828234384879271
step 3600 error value= 0.4383281894446155
step 4000 error value= 0.4011469664169937
step 4400 error value= 0.3696191588956381
step 4800 error value= 0.342554522263804
step 5200 error value= 0.3190759762847003
step 5600 error value= 0.29852220603566837
step 6000 error value= 0.2803848221837423
step 6400 error value= 0.26426643659728244
step 6800 error value= 0.24985189157794396
step 7200 error value= 0.23688803395480862
step 7600 error value= 0.2251691961834138
step 8000 error value= 0.2145265817078536


In [10]:
# NAND Gate prediction
print(NAND_obj.name, '\n')

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for input_data in test_data:
    (sigmoidid_val, logical_val) = NAND_obj.predict(input_data)
    print( input_data, ' = ', logical_val, '\n')

NAND_GATE 

[0 0]  =  1 

[0 1]  =  1 

[1 0]  =  1 

[1 1]  =  0 



In [11]:
# XOR 게이트 훈련
xdata = np.array([ [0,0],[0,1],[1,0],[1,1] ])
tdata = np.array([ 0,1,1,0 ])

XOR_obj = LogicGate("XOR_GATE", xdata, tdata)
XOR_obj.train()

Initial loss_func : 3.272203018444964
step 0 error value= 3.2595932300192194
step 400 error value= 2.778058053675072
step 800 error value= 2.7736094978284944
step 1200 error value= 2.7728059125394
step 1600 error value= 2.7726400409527683
step 2000 error value= 2.772601388923145
step 2400 error value= 2.772591562823755
step 2800 error value= 2.7725889302783493
step 3200 error value= 2.7725882047295234
step 3600 error value= 2.7725880018702425
step 4000 error value= 2.772587944750362
step 4400 error value= 2.7725879286119373
step 4800 error value= 2.7725879240447835
step 5200 error value= 2.7725879227512724
step 5600 error value= 2.7725879223847874
step 6000 error value= 2.772587922280934
step 6400 error value= 2.772587922251502
step 6800 error value= 2.7725879222431606
step 7200 error value= 2.772587922240797
step 7600 error value= 2.7725879222401266
step 8000 error value= 2.7725879222399366


In [15]:
# XOR Gate prediction
print(XOR_obj.name, '\n')

test_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

for input_data in test_data:
    (sigmoidid_val, logical_val) = XOR_obj.predict(input_data)
    print( input_data, ' = ', logical_val, '\n')
    print(XOR_obj.predict(input_data), '\n')
    
# 결과값 오류오 인해 (XOR = NAND + OR)조합으로 계산해서 XOR 학습시켜야함!!!

XOR_GATE 

[0 0]  =  0 

(array([0.49999984]), 0) 

[0 1]  =  0 

(array([0.49999998]), 0) 

[1 0]  =  0 

(array([0.49999998]), 0) 

[1 1]  =  1 

(array([0.50000011]), 1) 



In [13]:
# XOR = NAND + OR 조합으로 계산
input_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

s1 = []  # NAND 출력
s2 = []  # OR 출력

new_input_data = []  # AND 입력
final_output = []    # AND 출력

for index in range(len(input_data)):
    
    s1 = NAND_obj.predict(input_data[index])  # NAND 출력
    s2 = OR_obj.predict(input_data[index])    # OR 출력
    # s1 = 1, 1, 1, 0
    # s2 = 0, 1, 1, 1
    
    
    new_input_data.append(s1[-1])   # AND 입력
    new_input_data.append(s2[-1])   # AND 입력
    
    (sigmoid_val, logical_val) = AND_obj.predict(np.array(new_input_data))
    
    final_output.append(logical_val)  # AND 출력, 즉 XOR 출력
    new_input_data = []  # AND 입력 초기화
    
for index in range(len(input_data)):
    print( input_data[index], ' = ', final_output[index], end='')
    print( '\n' )

[0 0]  =  0

[0 1]  =  1

[1 0]  =  1

[1 1]  =  0



In [14]:
for input_data in test_data:
    print(XOR_obj.predict(input_data))

(array([0.49999984]), 0)
(array([0.49999998]), 0)
(array([0.49999998]), 0)
(array([0.50000011]), 1)
